### PR TITLE
Added icons for position/rotation/scale animation key

### PR DESCRIPTION
**Pull request by letheed**
Icons for the `loc`, `rot` and `scl` animation key buttons. I kept the current scheme green/red for enabled/disabled and reused the tool icons but replaced the circle with the keys' rectangle.

key_icons

### CODE REVIEW

**Comment by djrm** [comment]
hmm, i like them, however the color coding is not that, red is for remove, green is for add, since those buttons are not adding nor removing, i would suggest to make the enable plain grey (or with they key icon blue like the key selected), and the disabled semi transparent.

**Comment by letheed** [comment]
Yeah I thought about doing that, my fear was that they would look too much like the default tool icons and that'd be confusing. I'll push that in a moment.

**Comment by letheed** [comment]
Preview and a variant I tried:

1. key_icons 3
2. key_icons 2

**Comment by djrm** [comment]
@letheed both look good, feel free to use the variation you like better.

**Comment by letheed** [comment]
No, the first is better I think, it was a good idea to use the blue key.

**Pull request merged**
